// Module map with PM and Slack IDs — keyed by exact module name from Jira
export const MODULES = {
  Acknowledgements: { pm: 'Delfina Pipan', slackId: 'U067SMZ18KB' },
  Anniversaries: { pm: 'Barbara Aliprandi', slackId: 'U05TC8QBX39' },
  Automations: { pm: 'Martin Ciccioli', slackId: 'U02SEQUGJ78' },
  ATS: { pm: 'Manuela Cavallo', slackId: 'U08N6R7G03U' },
  Auth: { pm: 'Agustina Ini', slackId: 'U05TRT1BS78' },
  Calls: { pm: 'Fermin Castro Madero', slackId: 'U06RUNGDN0Y' },
  ChatBots: { pm: 'Cristian Baltazar', slackId: 'U05ASJS4F1S' },
  Chats: { pm: 'Luciano Paradiso', slackId: 'U05FFDZ4CQH' },
  Documents: { pm: null, slackId: null },
  Events: { pm: 'Carolina Arditi', slackId: 'U05R2440NN5' },
  Feed: { pm: 'Barbara Aliprandi', slackId: 'U05TC8QBX39' },
  Files: { pm: null, slackId: null },
  Forms: { pm: 'Carolina Arditi', slackId: 'U05R2440NN5' },
  Goals: { pm: 'Cristian Baltazar', slackId: 'U05ASJS4F1S' },
  Groups: { pm: 'Barbara Aliprandi', slackId: 'U05TC8QBX39' },
  Insights: { pm: null, slackId: null },
  Integrations: { pm: null, slackId: null },
  Learning: { pm: 'Delfina Pipan', slackId: 'U067SMZ18KB' },
  Libraries: { pm: 'Delfina Pipan', slackId: 'U067SMZ18KB' },
  Livestream: { pm: 'Fermin Castro Madero', slackId: 'U06RUNGDN0Y' },
  Marketplace: { pm: 'Barbara Aliprandi', slackId: 'U05TC8QBX39' },
  News: { pm: 'Barbara Aliprandi', slackId: 'U05TC8QBX39' },
  'Notification Center': { pm: 'Cristian Baltazar', slackId: 'U05ASJS4F1S' },
  Onboarding: { pm: 'Juan Diego Alcocer', slackId: 'U06T3HRA1EZ' },
  'Org Chart': { pm: 'Delfina Pipan', slackId: 'U067SMZ18KB' },
  'People Exp': { pm: null, slackId: null },
  'Perf Review': { pm: null, slackId: null },
  Profile: { pm: null, slackId: null },
  Recognitions: { pm: 'Barbara Aliprandi', slackId: 'U05TC8QBX39' },
  Sammy: { pm: null, slackId: null },
  Schedules: { pm: null, slackId: null },
  'Service Mgmt': { pm: null, slackId: null },
  Surveys: { pm: null, slackId: null },
  'Time Off': { pm: null, slackId: null },
  'Time Tracking': { pm: null, slackId: null },
  Trainings: { pm: 'Delfina Pipan', slackId: 'U067SMZ18KB' },
  Users: { pm: 'Agustina Ini', slackId: 'U05TRT1BS78' },
  Workflows: { pm: 'Martin Ciccioli', slackId: 'U02SEQUGJ78' },
  General: { pm: null, slackId: null },
};

export const MODULE_NAMES = Object.keys(MODULES);
