// Module map with PM and Slack IDs — keyed by exact module name from Jira.
// Source: "Mini Apps ownership by Squad" (Notion) cross-checked against Jira's
// "Mini App" field, with Slack member IDs confirmed by the team (2026-09-24).
export const MODULES = {
  'AI Agents': { pm: 'Mariana Szewach', slackId: 'U0B92EHJ43T' },
  Audience: { pm: 'Agustina Ini', slackId: 'U05TRT1BS78' },
  Auth: { pm: 'Agustina Ini', slackId: 'U05TRT1BS78' },
  Automations: { pm: 'Martin Ciccioli', slackId: 'U02SEQUGJ78' },
  Calls: { pm: 'Juan Ignacio Rios', slackId: 'U08RLMMBUPJ' },
  'Career path': { pm: 'Cristian Baltazar', slackId: 'U05ASJS4F1S' },
  Celebrations: { pm: 'Franco Virzi', slackId: 'U0ABYN2U5K6' },
  ChatBots: { pm: 'Cristian Baltazar', slackId: 'U05ASJS4F1S' },
  Chats: { pm: 'Nicolas Cordes', slackId: 'U05L0GPA5CZ' },
  Competencies: { pm: 'Cristian Baltazar', slackId: 'U05ASJS4F1S' },
  'Core Forms': { pm: 'Martin Ciccioli', slackId: 'U02SEQUGJ78' },
  'Discover Humand': { pm: 'Victoria Castagnaro', slackId: 'U0AHKGU20AE' },
  Documents: { pm: 'Luciano Paradiso', slackId: 'U05FFDZ4CQH' },
  Events: { pm: 'Juan Ignacio Rios', slackId: 'U08RLMMBUPJ' },
  Feed: { pm: 'Barbara Aliprandi', slackId: 'U05TC8QBX39' },
  'File Assets': { pm: 'Martin Ciccioli', slackId: 'U02SEQUGJ78' },
  Files: { pm: 'Luciano Paradiso', slackId: 'U05FFDZ4CQH' },
  Forms: { pm: 'Carolina Arditi', slackId: 'U05R2440NN5' },
  Goals: { pm: 'Cristian Baltazar', slackId: 'U05ASJS4F1S' },
  Groups: { pm: 'Barbara Aliprandi', slackId: 'U05TC8QBX39' },
  Insights: { pm: 'Ari Karzovinik', slackId: 'U0ANQM4CAR4' },
  Integrations: { pm: null, slackId: null },
  Acknowledgements: { pm: 'Franco Virzi', slackId: 'U0ABYN2U5K6' },
  Learning: { pm: 'Delfina Pipan', slackId: 'U067SMZ18KB' },
  'Legajo digital | HRIS': { pm: 'Camila Pacin', slackId: 'U0AG20S72BT' },
  Libraries: { pm: 'Delfina Pipan', slackId: 'U067SMZ18KB' },
  Livestream: { pm: 'Juan Ignacio Rios', slackId: 'U08RLMMBUPJ' },
  Marketplace: { pm: 'Barbara Aliprandi', slackId: 'U05TC8QBX39' },
  Microloans: { pm: 'Victoria Castagnaro', slackId: 'U0AHKGU20AE' },
  News: { pm: 'Barbara Aliprandi', slackId: 'U05TC8QBX39' },
  Notifications: { pm: null, slackId: null },
  Oli: { pm: 'Mariana Szewach', slackId: 'U0B92EHJ43T' },
  Onboarding: { pm: 'Juan Diego Alcocer', slackId: 'U06T3HRA1EZ' },
  Ops: { pm: null, slackId: null },
  'Org Chart': { pm: 'Delfina Pipan', slackId: 'U067SMZ18KB' },
  'Payroll ARG': { pm: 'Nieves Rimoldi', slackId: 'U0BQ1GG0JJC' },
  'Payroll MX': { pm: 'Daniela Cativa', slackId: 'U0B11ALTT5M' },
  'People Experience': { pm: 'Leandro', slackId: 'U0C00BXVAQJ' },
  'Perf Review': { pm: 'Cristian Baltazar', slackId: 'U05ASJS4F1S' },
  Prode: { pm: 'Leandro', slackId: 'U0C00BXVAQJ' },
  Profile: { pm: 'Camila Pacin', slackId: 'U0AG20S72BT' },
  ATS: { pm: 'Siro Gallo', slackId: 'U0B8Z32RAJ2' },
  Referrals: { pm: 'Luciano Paradiso', slackId: 'U05FFDZ4CQH' },
  'Region/Sites': { pm: 'Augusto Ferrer', slackId: 'U063ZECFYE5' },
  'Roles/Perm': { pm: 'Agustina Ini', slackId: 'U05TRT1BS78' },
  'Sammy 2.0': { pm: 'Mariana Szewach', slackId: 'U0B92EHJ43T' },
  Search: { pm: 'Franco Virzi', slackId: 'U0ABYN2U5K6' },
  Security: { pm: 'Agustina Ini', slackId: 'U05TRT1BS78' },
  'Service Management': { pm: 'Carolina Arditi', slackId: 'U05R2440NN5' },
  'Shift Management': { pm: 'Stephanie Silberman', slackId: 'U0AR8BX443F' },
  'Sockets Service': { pm: 'Nicolas Cordes', slackId: 'U05L0GPA5CZ' },
  Surveys: { pm: 'Carolina Arditi', slackId: 'U05R2440NN5' },
  'Task Manager': { pm: 'Juan Diego Alcocer', slackId: 'U06T3HRA1EZ' },
  'Time Off': { pm: 'Tiziana Rassow', slackId: 'U0B66BU8B5G' },
  'Time Tracking': { pm: 'Augusto Ferrer', slackId: 'U063ZECFYE5' },
  'User Management': { pm: 'Camila Pacin', slackId: 'U0AG20S72BT' },
  Widgets: { pm: null, slackId: null },
  'Work Schedules': { pm: 'Stephanie Silberman', slackId: 'U0AR8BX443F' },
  Workflows: { pm: 'Carolina Arditi', slackId: 'U05R2440NN5' },
  General: { pm: null, slackId: null },
};

export const MODULE_NAMES = Object.keys(MODULES);
