// Module map with PM and Slack IDs — keyed by exact module name from Jira.
// Source: Jira's actual "Mini App" field picklist (confirmed by the team, 2026-10-06),
// with PM/Slack IDs carried over from the Notion-derived list where a module matched.
export const MODULES = {
  Acknowledgements: { pm: 'Franco Virzi', slackId: 'U0ABYN2U5K6' },
  Audiences: { pm: 'Agustina Ini', slackId: 'U05TRT1BS78' },
  Automations: { pm: 'Martin Ciccioli', slackId: 'U02SEQUGJ78' },
  ATS: { pm: 'Siro Gallo', slackId: 'U0B8Z32RAJ2' },
  Auth: { pm: 'Agustina Ini', slackId: 'U05TRT1BS78' },
  Calls: { pm: 'Juan Ignacio Rios', slackId: 'U08RLMMBUPJ' },
  Celebrations: { pm: 'Franco Virzi', slackId: 'U0ABYN2U5K6' },
  ChatBots: { pm: 'Cristian Baltazar', slackId: 'U05ASJS4F1S' },
  Chats: { pm: 'Nicolas Cordes', slackId: 'U05L0GPA5CZ' },
  'Core Forms': { pm: 'Martin Ciccioli', slackId: 'U02SEQUGJ78' },
  Documents: { pm: 'Luciano Paradiso', slackId: 'U05FFDZ4CQH' },
  'Emp Lifecycle': { pm: null, slackId: null },
  Events: { pm: 'Juan Ignacio Rios', slackId: 'U08RLMMBUPJ' },
  Feed: { pm: 'Barbara Aliprandi', slackId: 'U05TC8QBX39' },
  Files: { pm: 'Luciano Paradiso', slackId: 'U05FFDZ4CQH' },
  Forms: { pm: 'Carolina Arditi', slackId: 'U05R2440NN5' },
  Goals: { pm: 'Cristian Baltazar', slackId: 'U05ASJS4F1S' },
  Groups: { pm: 'Barbara Aliprandi', slackId: 'U05TC8QBX39' },
  Insights: { pm: 'Ari Karzovinik', slackId: 'U0ANQM4CAR4' },
  Integrations: { pm: null, slackId: null },
  Learning: { pm: 'Delfina Pipan', slackId: 'U067SMZ18KB' },
  Libraries: { pm: 'Delfina Pipan', slackId: 'U067SMZ18KB' },
  Livestream: { pm: 'Juan Ignacio Rios', slackId: 'U08RLMMBUPJ' },
  Marketplace: { pm: 'Barbara Aliprandi', slackId: 'U05TC8QBX39' },
  'Micro Creditos': { pm: 'Victoria Castagnaro', slackId: 'U0AHKGU20AE' },
  News: { pm: 'Barbara Aliprandi', slackId: 'U05TC8QBX39' },
  Notifications: { pm: null, slackId: null },
  Onboarding: { pm: 'Juan Diego Alcocer', slackId: 'U06T3HRA1EZ' },
  Oli: { pm: 'Mariana Szewach', slackId: 'U0B92EHJ43T' },
  'Org Chart': { pm: 'Delfina Pipan', slackId: 'U067SMZ18KB' },
  Ops: { pm: null, slackId: null },
  'People Exp': { pm: 'Leandro', slackId: 'U0C00BXVAQJ' },
  'Perf Review': { pm: 'Cristian Baltazar', slackId: 'U05ASJS4F1S' },
  Prode: { pm: 'Leandro', slackId: 'U0C00BXVAQJ' },
  Profile: { pm: 'Camila Pacin', slackId: 'U0AG20S72BT' },
  Referrals: { pm: 'Luciano Paradiso', slackId: 'U05FFDZ4CQH' },
  'Region/Sites': { pm: 'Augusto Ferrer', slackId: 'U063ZECFYE5' },
  'Roles/Perm': { pm: 'Agustina Ini', slackId: 'U05TRT1BS78' },
  Sammy: { pm: null, slackId: null },
  'Sammy 2.0': { pm: 'Mariana Szewach', slackId: 'U0B92EHJ43T' },
  Search: { pm: 'Franco Virzi', slackId: 'U0ABYN2U5K6' },
  'Service Mgmt': { pm: 'Carolina Arditi', slackId: 'U05R2440NN5' },
  Surveys: { pm: 'Carolina Arditi', slackId: 'U05R2440NN5' },
  'Time Off': { pm: 'Tiziana Rassow', slackId: 'U0B66BU8B5G' },
  'Time Planning': { pm: null, slackId: null },
  'Time Tracking': { pm: 'Augusto Ferrer', slackId: 'U063ZECFYE5' },
  Users: { pm: 'Camila Pacin', slackId: 'U0AG20S72BT' },
  Widgets: { pm: null, slackId: null },
  Workflows: { pm: 'Carolina Arditi', slackId: 'U05R2440NN5' },
  General: { pm: null, slackId: null },
  Internal: { pm: null, slackId: null },
  // "Payroll" and "Trainings" are valid Jira values with no confirmed PM yet —
  // left out on purpose so they show "Sin PM asignado" instead of a guess.
};

export const MODULE_NAMES = Object.keys(MODULES);
